// Barrel exports for all hooks
export { useUserProfile, useTechnicianProfile, useUpdateProfile, useChangePassword } from './useProfile'
export { useMyJobs, useJobDetail, useJobStats, useUpdateJobStatus, useUpdateJob, useUpdateCustomFields } from './useJobs'
export { useWorkOrdersByJob, useWorkOrderDetail, useCheckIn, useCheckOut, useCompleteTask, useAddLineItem, useRemoveLineItem, usePriceBook } from './useWorkOrders'
export { useMyAssignments, useAssignmentDetail, useJobAssignments, useUpdateAssignmentStatus, useSendGps } from './useSchedule'
export { useNotifications, useUnreadCount, useMarkRead, useMarkAllRead } from './useNotifications'
export { useThreads, useThreadDetail, useSendMessage, useMarkThreadRead, useCreateThread } from './useMessages'
export { useMyExpenses, useExpenseDetail, useCreateExpense } from './useExpenses'
export { useCustomerDetail } from './useCustomer'
export { useGPSTracking, requestLocationPermissions, getCurrentLocation } from './useGPS'
export { useLocations, useMyVanLocation, useVanStock, useMyMovements, useConfirmTransfer, toNumber } from './useInventory'
