#!/usr/bin/env bash
# ============================================================
# T&S CRM — Generate service .env files from root .env
# Ensures every service has the correct env vars locally.
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

# Source root .env to read values
set -a
source .env 2>/dev/null || true
set +a

# Defaults for vars that might not be in root .env
BYPASS_AUTH="${BYPASS_AUTH:-true}"
JWT_SECRET="${JWT_SECRET:-tscrm-local-jwt-secret-change-in-production}"
CRM_DATABASE_URL="${CRM_DATABASE_URL:-postgresql://tscrm_user:tscrm_pass@localhost:5432/tscrm?schema=crm}"
JOBS_DATABASE_URL="${JOBS_DATABASE_URL:-postgresql://tscrm_user:tscrm_pass@localhost:5432/tscrm?schema=jobs}"
FINANCE_DATABASE_URL="${FINANCE_DATABASE_URL:-postgresql://tscrm_user:tscrm_pass@localhost:5432/tscrm?schema=finance}"
ANALYTICS_DATABASE_URL="${ANALYTICS_DATABASE_URL:-postgresql://tscrm_user:tscrm_pass@localhost:5432/tscrm?schema=analytics}"
INVENTORY_DATABASE_URL="${INVENTORY_DATABASE_URL:-postgresql://tscrm_user:tscrm_pass@localhost:5432/tscrm?schema=inventory}"
SCHEDULING_DATABASE_URL="${SCHEDULING_DATABASE_URL:-postgresql://tscrm_user:tscrm_pass@localhost:5432/tscrm?schema=scheduling}"
MONGODB_URI_LOCAL="${MONGODB_URI:-mongodb://localhost:27017/tscrm_comms}"
REDIS_HOST="${REDIS_HOST:-localhost}"
REDIS_PORT="${REDIS_PORT:-6379}"

# ── CRM Service ────────────────────────────────────────────
cat > apps/crm-service/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
CRM_DATABASE_URL=${CRM_DATABASE_URL}
CRM_PORT=${CRM_PORT:-3001}
BYPASS_AUTH=${BYPASS_AUTH}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=development
COMMS_SERVICE_URL=http://localhost:${COMMS_PORT:-3005}
EOF

# ── Job Service ────────────────────────────────────────────
cat > apps/job-service/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
JOBS_DATABASE_URL=${JOBS_DATABASE_URL}
JOBS_PORT=${JOBS_PORT:-3002}
BYPASS_AUTH=${BYPASS_AUTH}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=development
EOF

# ── Scheduling Service (Go) ───────────────────────────────
cat > apps/scheduling-service/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
DATABASE_URL=postgresql://tscrm_user:tscrm_pass@localhost:5432/tscrm?search_path=scheduling
REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
SCHEDULING_PORT=${SCHEDULING_PORT:-3003}
BYPASS_AUTH=${BYPASS_AUTH}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=development
EOF

# ── Finance Service ────────────────────────────────────────
cat > apps/finance-service/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
DATABASE_URL=${FINANCE_DATABASE_URL}
FINANCE_PORT=${FINANCE_PORT:-3004}
BYPASS_AUTH=${BYPASS_AUTH}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=development
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_placeholder}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_placeholder}
CHROMIUM_PATH=
EOF

# ── Comms Service ──────────────────────────────────────────
cat > apps/comms-service/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
MONGODB_URI=mongodb://localhost:27017/tscrm_comms?replicaSet=rs0
COMMS_PORT=${COMMS_PORT:-3005}
REDIS_HOST=${REDIS_HOST}
REDIS_PORT=${REDIS_PORT}
BYPASS_AUTH=${BYPASS_AUTH}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=development
# SMS/Email — leave as placeholders for local dev (messages are logged, not sent)
TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID:-ACxxxxxxxx}
TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN:-xxxxxxxx}
TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER:-+1xxxxxxxxxx}
SENDGRID_API_KEY=${SENDGRID_API_KEY:-SG.xxxxxxxx}
EXPO_ACCESS_TOKEN=${EXPO_ACCESS_TOKEN:-xxxxxxxx}
SMTP_HOST=
SMTP_PORT=
SMTP_USER=
SMTP_PASS=
SMTP_FROM=
EOF

# ── Analytics Service ──────────────────────────────────────
cat > apps/analytics-service/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
ANALYTICS_DATABASE_URL=${ANALYTICS_DATABASE_URL}
ANALYTICS_PORT=${ANALYTICS_PORT:-3006}
BYPASS_AUTH=${BYPASS_AUTH}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=development
EOF

# ── Inventory Service ──────────────────────────────────────
cat > apps/inventory-service/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
INVENTORY_DATABASE_URL=${INVENTORY_DATABASE_URL}
INVENTORY_PORT=${INVENTORY_PORT:-3007}
BYPASS_AUTH=${BYPASS_AUTH}
JWT_SECRET=${JWT_SECRET}
NODE_ENV=development
EOF

# ── Admin Dashboard ────────────────────────────────────────
cat > apps/admin-dashboard/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
VITE_COMPANY_ID=co-demo-001
VITE_COMPANY_NAME=${VITE_COMPANY_NAME:-T&S Services}
VITE_COMPANY_ADDRESS=${VITE_COMPANY_ADDRESS:-123 Main St, Suite 100, London, UK}
VITE_COMPANY_PHONE=${VITE_COMPANY_PHONE:-+44 20 1234 5678}
VITE_COMPANY_EMAIL=${VITE_COMPANY_EMAIL:-info@tsservices.com}
VITE_COMPANY_WEBSITE=${VITE_COMPANY_WEBSITE:-www.tsservices.com}
VITE_COMPANY_ABN=${VITE_COMPANY_ABN:-}
EOF

# ── Customer Portal ────────────────────────────────────────
cat > apps/customer-portal/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
VITE_COMPANY_ID=co-demo-001
EOF

# ── Technician App ─────────────────────────────────────────
# Detect local IP for Expo (mobile device needs LAN IP)
LOCAL_IP=$(ipconfig getifaddr en0 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
cat > apps/technician-app/.env << EOF
# Auto-generated by scripts/generate-env.sh — do not edit manually
EXPO_PUBLIC_API_BASE_URL=http://${LOCAL_IP}:80/api
EXPO_PUBLIC_COMPANY_ID=co-demo-001
EOF

echo "  All service .env files generated from root .env"
