-- ============================================================
-- Migration 002: Relax company_id / user_id to TEXT
-- ============================================================
-- The rest of the platform uses opaque string IDs for company/user
-- (e.g. "co-demo-001" in dev mode, Auth0 sub strings in prod).
-- PostgreSQL UUID columns reject these, causing 22P02 errors.
-- All UUID PKs (id) and FK references to technicians.id are kept
-- as UUID because those are generated by uuid_generate_v4().
-- ============================================================

-- Drop indexes that reference the affected columns first so ALTER doesn't fail
DROP INDEX IF EXISTS scheduling.idx_technicians_company;
DROP INDEX IF EXISTS scheduling.idx_technicians_active;
DROP INDEX IF EXISTS scheduling.idx_shifts_company_date;
DROP INDEX IF EXISTS scheduling.idx_zones_company;
DROP INDEX IF EXISTS scheduling.idx_assignments_company;
DROP INDEX IF EXISTS scheduling.idx_assignments_status;
DROP INDEX IF EXISTS scheduling.idx_assignments_scheduled;
DROP INDEX IF EXISTS scheduling.idx_gps_company;

-- scheduling.technicians
ALTER TABLE scheduling.technicians
  ALTER COLUMN company_id TYPE TEXT,
  ALTER COLUMN user_id    TYPE TEXT;

-- scheduling.technician_shifts
ALTER TABLE scheduling.technician_shifts
  ALTER COLUMN company_id TYPE TEXT;

-- scheduling.service_zones
ALTER TABLE scheduling.service_zones
  ALTER COLUMN company_id TYPE TEXT;

-- scheduling.dispatch_assignments
ALTER TABLE scheduling.dispatch_assignments
  ALTER COLUMN company_id   TYPE TEXT,
  ALTER COLUMN job_id       TYPE TEXT,
  ALTER COLUMN work_order_id TYPE TEXT,
  ALTER COLUMN assigned_by  TYPE TEXT;

-- scheduling.gps_tracking
ALTER TABLE scheduling.gps_tracking
  ALTER COLUMN company_id TYPE TEXT;

-- Re-create the dropped indexes
CREATE INDEX idx_technicians_company  ON scheduling.technicians(company_id);
CREATE INDEX idx_technicians_active   ON scheduling.technicians(company_id, is_active);
CREATE INDEX idx_shifts_company_date  ON scheduling.technician_shifts(company_id, shift_date);
CREATE INDEX idx_zones_company        ON scheduling.service_zones(company_id);
CREATE INDEX idx_assignments_company  ON scheduling.dispatch_assignments(company_id);
CREATE INDEX idx_assignments_status   ON scheduling.dispatch_assignments(company_id, status);
CREATE INDEX idx_assignments_scheduled ON scheduling.dispatch_assignments(company_id, scheduled_start);
CREATE INDEX idx_gps_company          ON scheduling.gps_tracking(company_id, captured_at DESC);
